apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-site-frontend
spec:
  replicas: 1
  template:
    metadata:
      name: personal-site-frontend
      labels:
        app: personal-site
        name: nickpalenchar
    spec:
      containers:
      - image: 939117166617.dkr.ecr.us-east-1.amazonaws.com/nickpalenchar:%version%
        name: nickpalenserver
---
apiVersion: v1
kind: Service
metadata:
  name: nickpalenchar
spec:
  type: LoadBalancer
  selector:
    name: nickpalenchar
  ports:
    - { port: 80, targetPort: 3333, name: http }
    - { port: 433, targetPort: 3333, name: https }
